In [1]:
import numpy as np

In [3]:
arr=np.array([2,3,4,5])
new=arr+5
print(new)
print(arr)

[ 7  8  9 10]
[2 3 4 5]


In [11]:
print(arr[2])

4


In [7]:
print(arr[::-1])

[5 4 3 2]


In [8]:
print(arr[1:])

[3 4 5]


In [9]:
sub=arr-5
print(sub)
mul=arr*5
print(mul)
div=arr/5
print(div)

[-3 -2 -1  0]
[10 15 20 25]
[0.4 0.6 0.8 1. ]


In [12]:
print(np.sum(arr))

14


In [13]:
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

5
2
3.5


In [20]:
a=arr.reshape(2,2)
print(a)

[[2 3]
 [4 5]]


In [19]:
import pandas as pd

In [37]:
data={
    "name":["mahatb","mahesh","nayeem"],
    "marks":[99,99,99],
    "branch":["cse","aiml","IS"]
}
hi=pd.DataFrame(data)
print(hi)

     name  marks branch
0  mahatb     99    cse
1  mahesh     99   aiml
2  nayeem     99     IS


In [38]:
print(hi["marks"])

0    99
1    99
2    99
Name: marks, dtype: int64


In [39]:
print(hi["name"])

0    mahatb
1    mahesh
2    nayeem
Name: name, dtype: object


In [29]:
print(hi.iloc[0])

name      mahatb
marks         99
branch       cse
Name: 0, dtype: object


In [30]:
print(hi.iloc[0,1])

99


In [31]:
print(hi.iloc[1,2])

aiml


In [33]:
print(hi.iloc[0:3,[0,1]])

     name  marks
0  mahatb     99
1  mahesh     99
2  nayeem     99


In [40]:
result=hi[hi["marks"]>90]
print(result)

     name  marks branch
0  mahatb     99    cse
1  mahesh     99   aiml
2  nayeem     99     IS
